[project]
name = "FastDownloaderGUI"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest>=9.0.2",
    "pywebview>=6.1",
    "requests>=2.32.5",
    "websockets>=15.0.1",
    "wxpython>=4.2.4",
]

[dependency-groups]
build = [
    "nuitka>=2.8.9",
    "pyinstaller>=6.16.0",
]
dev = [
    "watchdog>=6.0.0",
]
